name: Abim checker (headless)

on:
  schedule:
    - cron: '*/20 * * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Chrome & Selenium
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser
          pip install selenium beautifulsoup4

      - name: Run Abim check
        env:
          CHROME_PATH: /usr/bin/chromium-browser
        run: python monitor.py

      - name: Commit result
        run: |
          git config user.name "Abim Bot"
          git config user.email "actions@github.com"
          git add index.html
          git commit -m "Abim update [skip ci]" || echo "No changes"
          git push
