name: Abim checker headless

on:
  schedule:
    - cron: "*/20 * * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Chrome
        id: setup-chrome
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: stable

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install selenium beautifulsoup4

      - name: Run Abim check
        env:
          CHROME_PATH: ${{ steps.setup-chrome.outputs.chrome-path }}
          LOGIN_EMAIL: ${{ secrets.LOGIN_EMAIL }}
          LOGIN_PASSWORD: ${{ secrets.LOGIN_PASSWORD }}
          CENTER_LIST: ${{ vars.CENTER_LIST }}
          CATEGORY_TEXT: ${{ vars.CATEGORY_TEXT }}
          SUBCATEGORY_TEXT: ${{ vars.SUBCATEGORY_TEXT }}
          HEADLESS: "1"
        run: python monitor.py

      - name: Commit result
        run: |
          git config user.name "Abim Bot"
          git config user.email "actions@github.com"
          git add index.html
          git commit -m "Abim update [skip ci]" || echo "No changes"
          git push
