name: Abim checker

on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: pip install requests beautifulsoup4
      - name: Run checker
        run: python monitor.py
      - name: Commit result if changed
        run: |
          git config user.name "Abim Bot"
          git config user.email "actions@github.com"
          # hash değişimini anlamak için eski commit ile diff
          git add index.html .abim_hash
          git diff --cached --quiet && echo "Değişiklik yok" || (git commit -m "Abim guncelleme [skip ci]" && git push)
